### ISSUE TITLE
Neo-tree Module git state colors not showing

### ISSUE THREAD

**Issue by Pernick** [EdenEast/nightfox.nvim#178] opened 2022-07-07 19:58 UTC
## Description

Neo-tree is not showing git colors no matter the configuration attributes such as `use_git_status_colors = true`. Is there any additional setup necessary for this plugin to work with neo-tree?

## Behavior

In the on the screenshot repository, there are many git changes which I want to show within the neo-tree. But all the folders and files have the same color no matter the git state.

**Screenshots**
![Screenshot 2022-07-07 at 21 56 30](https://user-images.githubusercontent.com/16494885/177861489-4734b2cf-9505-4af5-8ed7-1c4e9dd17806.png)

## Configuration

1. Open git repository with changes with nvim and attached `minimal_init.lua`
2. Run editor command `:Neotree toggle`

<details>
<summary>minimal_init.lua</summary>

```
local is_windows = vim.fn.has("win32") == 1
local function join(...)
  local sep = is_windows and "\\" or "/"
  return table.concat({ ... }, sep)
end

local root_tmp = is_windows and os.getenv("TEMP") or "/tmp"
local site_path = join(root_tmp, "nvim", "site")
local pack_path = join(site_path, "pack")
local install_path = join(pack_path, "packer", "start", "packer.nvim")
local compile_path = join(install_path, "plugin", "packer_compiled.lua")
vim.opt.packpath = site_path

local function load_plugins()
  local packer = require("packer")
  local use = packer.use
  packer.reset()
  packer.init({ compile_path = compile_path, package_root = pack_path })

  use("wbthomason/packer.nvim")
  use("EdenEast/nightfox.nvim")
  use {
    "nvim-neo-tree/neo-tree.nvim",
      branch = "v2.x",
      requires = { 
        "nvim-lua/plenary.nvim",
        "kyazdani42/nvim-web-devicons", -- not strictly required, but recommended
        "MunifTanjim/nui.nvim",
      }
    }
  -- ADD PLUGINS THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE

  packer.install()
end

_G.load_config = function()
  -- ADD INIT.LUA SETTINGS THAT ARE _NECESSARY_ FOR REPRODUCING THE ISSUE
  require("neo-tree").setup({
    default_component_configs = {
      name = {
        use_git_status_color = true,
        highlight = "NeoTreeFileName",
      }
    }
  })
  require("nightfox").setup({
    options = {
      transparent = true,
      terminal_colors = true,
      modules = {
        neotree = true
      }
    }
  })

  vim.cmd("colorscheme nordfox")
end

if vim.fn.isdirectory(install_path) == 0 then
  vim.fn.system({ "git", "clone", "--depth=1", "https://github.com/wbthomason/packer.nvim", install_path })
end
load_plugins()
vim.cmd([[autocmd User PackerComplete ++once echo "Ready!" | lua load_config()]])

```
</details>

## Additional info / context

nvim v0.7.0

**I am probably just missing something in the configuration, but I am unable to find what. Any help would be greatly appreciated, thanks!**

**Comment by EdenEast** [comment] 2022-07-07 23:34
I was unable to reproduce your issue with the `minimal_init` provided. Try to run `:NightfoxClean` to remove any compiled files generated.

<img width="969" alt="Screen Shot 2022-07-07 at 6 38 37 PM" src="https://user-images.githubusercontent.com/2746374/177888310-bcd14afd-b575-4c0e-8a1c-0e4f9b3ce587.png">

**Comment by Pernick** [comment] 2022-07-08 06:04
Hey, thanks for looking into this. I already tried `:NightfoxClean` and does not help with this issue.

This probably means that Tmux/Alacritty is the reason this is not working for me. I will update this with solution when I find it.

**Comment by EdenEast** [comment] 2022-07-08 13:02
Make sure that the font your terminal is using is a [nerd font](https://www.nerdfonts.com/) type font. For me I am using Hack nerd font.

**Comment by Pernick** [comment] 2022-07-08 13:04
It is Nerd Font, I tried several. I think it has to do with alacritty, possibly fish. Tmux seems to play no role in this.

**Comment by EdenEast** [comment] 2022-07-08 14:54
Closing as this is not related to nightfox.

**Closed by EdenEast** 2022-07-08 14:54 UTC
Labels: bug
